name: project_messai
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  
  google_fonts: ^4.0.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_animated_splash: ^0.0.10 
  country_code_picker: ^3.2.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  intl: ^0.20.2 #Dynamic Dates for slot.dart file 
  flutter_stripe: ^11.4.0 #Payment gateway
  http: ^1.3.0 
  
  # Add map:
  google_maps_flutter: ^2.10.1
  apple_maps_flutter: ^1.4.0

   # Firebase Dependencies
  firebase_core: ^3.12.0  # Required for Firebase initialization
  firebase_auth: ^5.5.0  # For authentication (Phone, Google, Email, etc.)
  cloud_firestore: ^5.6.4  # For Firestore database
  firebase_storage: ^12.4.3  # For storing images/files
  firebase_messaging: ^15.2.3  # For push notifications (if needed)
  firebase_analytics: ^11.4.3  # For app analytics (optional)
  google_sign_in: ^6.2.2 # for gmail sign-up
  csc_picker_plus: ^0.0.3 #for country list
  flutter_facebook_auth: ^7.1.1 #for facebook auth

dev_dependencies:
  
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"
  
  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0



  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

  min_sdk_android: 21 # android min sdk min:16, default 21
  



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


  assets:
    - assets/app_logo.png
    - assets/onboarding_1.png
    - assets/onboarding_2.png
    - assets/onboarding_3.png
    - assets\app_entrance.gif
    - assets/otp_bg.png
    - assets/otp_bg2.png
    - assets\google_logo.png
    - assets\login_bg.png
    - assets/forget_pswdbg.png
    - assets/successpswd.png
    - assets/promo_1.png
    - assets/painting.png
    - assets/wallpaper_works.png
    - assets/ceiling_gypsum.png
    - assets/tile_works.png
    - assets/promo_2.png
    - assets/ac.png
    - assets/plumbing.png
    - assets/electrical.png
    - assets/cctv.png
    - assets/manson.png
    - assets/promo_3.png
    - assets/carpenter.png
    - assets/gypsum_partition.png
    - assets/furniture_fitting.png
    - assets/curtain_interior.png
    - assets/polish_sign.png
    - assets/structure_frame.png
    - assets/welding_fab.png
    - assets/cleaning.png

    - assets/painter_banner.png
    - assets/off_white_paint.png
    - assets/color_paint.png
    - assets/water_damage.png
    
    - assets\wallpaper_banner.png
    - assets/wallpaper_repair.png
    - assets/wallpaper_removal.png
    - assets/wallpaper_installation.png 

    - assets/ceiling_gypsum_banner.png
    - assets/ceiling_gyp_inst.png
    - assets/ceiling_gyp_repair.png
    - assets/ceiling_gyp_mold.png

    - assets/gypsum_partition_banner.png
    - assets/gypsum_custom.png
    - assets/gypsum_installation.png
    - assets/gypsum_repair.png

    - assets/tile_banner.png
    - assets/tile_install.png
    - assets/tile_grout.png
    - assets/tile_repair.png

    - assets/ac_banner.png
    - assets/ac_duct.png
    - assets/ac_repair.png
    - assets/ac_split.png
    - assets/ac_win.png

    - assets/plumber_banner.png
    - assets/plumb_blk_drain.png
    - assets/plumb_book_4_30mints.png
    - assets/plumb_book_hrly.png
    - assets/plumb_leakage.png
    - assets/plumb_toilet.png
    - assets/plumb_tap.png

    - assets/electrical_banner.png
    - assets/ele_Book_4_30mints.png
    - assets/ele_Book_hrly.png
    - assets/ele_bulb.png
    - assets/ele_switch.png
    - assets/ele_tv.png
    - assets/ele_wire.png

    - assets/cctv_banner.png
    - assets/cctv_repair.png
    - assets/cctv_install.png
    - assets/ceiling_gyp_mold.png

    - assets/mason_banner.png
    - assets/mason_brick.png
    - assets/mason_concrete.png

    - assets/carpenter_banner.png
    - assets/car_fur_repair.png
    - assets/car_wood_install.png
    - assets/car_wood_work.png

    - assets/furniture_banner.png
    - assets/furniture_install.png
    - assets/furniture_repair.png

    - assets/curtain_banner.png
    - assets/curtain_install.png
    - assets/curtain_home_office.png

    - assets/polish_banner.png
    - assets/pol_sign.png
    - assets/pol_wood_furn.png

    - assets/structure_frame_banner.png
    - assets/str_steel.png
    - assets/str_wood_roof.png
    
    - assets/welding_banner.png
    - assets/weld_steel.png
    - assets/weld_grill.png

    - assets/cleaning_banner.png
    - assets/clean_commercial.png
    - assets/clean_house.png
    